using System.Text;
using DummyCameras.Infra;

namespace DummyCameras.MediaMtx;

/// <summary>
/// mediamtx.yml for the dummy farm (pure). Everything binds 127.0.0.1; only RTSP (+ the loopback API for readiness) is on.
/// Publishing: anonymous from loopback. Reading: the camera account (like a real camera) with Basic + Digest,
/// per-path - a camera with auth-fail gets no read grant, so its stream always answers 401.
/// </summary>
public static class MediaMtxConfig
{
    public sealed record Settings(
        int RtspPort,
        int RtpPort,
        int ApiPort,
        string User,
        string Password,
        bool AnonymousRead);

    public static string Build(Settings s, IEnumerable<CameraSpec> cameras)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# generated by tools/dummy-cameras - loopback only");
        sb.AppendLine("logLevel: info");
        sb.AppendLine("logDestinations: [stdout]");
        sb.AppendLine("readTimeout: 10s");
        sb.AppendLine("writeTimeout: 10s");
        sb.AppendLine("authMethod: internal");
        sb.AppendLine("authInternalUsers:");
        sb.AppendLine("  - user: any");
        sb.AppendLine("    pass:");
        sb.AppendLine("    ips: [\"127.0.0.1\", \"::1\"]");
        sb.AppendLine("    permissions:");
        sb.AppendLine("      - action: publish");
        sb.AppendLine("      - action: api");
        if (s.AnonymousRead) sb.AppendLine("      - action: read");

        var readable = cameras.Where(c => !c.Faults.AuthFail).SelectMany(c => c.Paths).ToList();
        if (!s.AnonymousRead && readable.Count > 0)
        {
            sb.AppendLine($"  - user: {Q(s.User)}");
            sb.AppendLine($"    pass: {Q(s.Password)}");
            sb.AppendLine("    ips: []");
            sb.AppendLine("    permissions:");
            foreach (var p in readable)
            {
                sb.AppendLine("      - action: read");
                sb.AppendLine($"        path: {Q(p)}");
            }
        }

        sb.AppendLine("api: true");
        sb.AppendLine($"apiAddress: 127.0.0.1:{s.ApiPort}");
        sb.AppendLine("metrics: false");
        sb.AppendLine("pprof: false");
        sb.AppendLine("playback: false");
        sb.AppendLine("rtsp: true");
        sb.AppendLine("rtspTransports: [udp, tcp]");
        sb.AppendLine("rtspEncryption: \"no\"");
        sb.AppendLine($"rtspAddress: 127.0.0.1:{s.RtspPort}");
        sb.AppendLine($"rtpAddress: 127.0.0.1:{s.RtpPort}");
        sb.AppendLine($"rtcpAddress: 127.0.0.1:{s.RtpPort + 1}");
        sb.AppendLine("rtspAuthMethods: [basic, digest]");
        sb.AppendLine("rtmp: false");
        sb.AppendLine("hls: false");
        sb.AppendLine("webrtc: false");
        sb.AppendLine("srt: false");
        sb.AppendLine("moq: false");
        sb.AppendLine("paths:");
        sb.AppendLine("  all_others:");
        return sb.ToString();
    }

    /// <summary>YAML double-quoted scalar.</summary>
    private static string Q(string s) => "\"" + s.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";
}
