'use strict';
const fs=require('fs'),path=require('path'),os=require('os'),assert=require('assert/strict'),{spawn}=require('child_process'),{CDP}=require('./test_ui_browser');
const {repository,git}=require('../../.claude/hooks/_harness-store'),{Coordinator}=require('../../.claude/hooks/_coordinator'),{startServer}=require('../../.claude/hooks/_ui-server');
const root=fs.mkdtempSync(path.join(os.tmpdir(),'harness-session-browser-')),project=path.join(root,'project'),profile=path.join(root,'browser'),mode=process.env.HARNESS_TEST_MODE||'headless',out=process.env.HARNESS_BROWSER_EVIDENCE||path.join(root,'evidence');let repo,server,client,child,c,checks=0;const credentials=[];
const sleep=ms=>new Promise(r=>setTimeout(r,ms));async function check(name,fn){await fn();checks++;console.log('PASS '+name);}
(async()=>{
 fs.mkdirSync(project);fs.mkdirSync(profile);fs.mkdirSync(out,{recursive:true});git(project,['init','-q']);repo=repository(project);c=new Coordinator(repo.store,{repo_id:repo.repo_id});server=await startServer(project,{context:repo});
 const work=c.createWork({track:'C',title:'로그인 화면과 서버',nodes:[{id:'frontend',title:'로그인 화면',files:['ui.txt']},{id:'backend',title:'서버 구현',files:['server.txt']}]});c.authorize(work.work_id,{source:'user',reference:'session UI test'},work.graph_hash);
 function session(runtime,name,work_id=work.work_id,pid=process.pid){const s=c.join({runtime,name,work_id,worktree:project,pid});credentials.push(s);return s;}
 const a=session('claude','Claude 화면'),b=session('codex','Codex 서버');
 const ca=c.claim(a,work.work_id,'frontend'),cb=c.claim(b,work.work_id,'backend');c.start(a,work.work_id,'frontend',ca.run_id,ca.epoch);c.start(b,work.work_id,'backend',cb.run_id,cb.epoch);
 repo.store.transaction(tx=>{for(const [s,n]of [[a,ca],[b,cb]])tx.put('agent/'+s.session_id,{agent_id:s.session_id,session_id:s.session_id,work_id:work.work_id,node_id:n.node_id,run_id:n.run_id,epoch:n.epoch,role:'implementation',status:'running',requested_model:'selected-only',execution_runtime:s.runtime,started_at:Date.now()},0);tx.put('agent/old',{agent_id:'old',session_id:a.session_id,work_id:work.work_id,node_id:'frontend',run_id:'old',status:'running',role:'review',requested_model:'old-model'},0);});
 const conflict=c.createWork({track:'B',title:'겹치는 화면 수정',nodes:[{id:'waiting',files:['ui.txt']}]});c.authorize(conflict.work_id,{source:'user',reference:'test'},conflict.graph_hash);const waiting=session('codex','Codex 대기',conflict.work_id);c.claim(waiting,conflict.work_id,'waiting');
 const orphan=c.createWork({track:'B',title:'복구할 작업',nodes:[{id:'recover',files:['recover.txt']}]});c.authorize(orphan.work_id,{source:'user',reference:'test'},orphan.graph_hash);const dead=session('claude','끊긴 세션',orphan.work_id,2147483000);c.claim(dead,orphan.work_id,'recover');
 const old=session('claude','지난 세션');c.leave(old);
 const browser=process.env.HARNESS_BROWSER||['C:/Program Files/Google/Chrome/Application/chrome.exe','C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'].find(fs.existsSync);assert.ok(browser);child=spawn(browser,['--remote-debugging-port=0','--user-data-dir='+profile,'--window-size=1600,1100','--no-first-run','--no-default-browser-check',...(mode==='headless'?['--headless=new']:[]),'about:blank'],{windowsHide:mode==='headless',stdio:'ignore'});
 const portFile=path.join(profile,'DevToolsActivePort');for(let i=0;i<120&&!fs.existsSync(portFile);i++)await sleep(100);const port=Number(fs.readFileSync(portFile,'utf8').split('\n')[0]),tabs=await(await fetch('http://127.0.0.1:'+port+'/json')).json();client=await CDP.connect(tabs.find(t=>t.type==='page').webSocketDebuggerUrl);await client.call('Page.bringToFront');await client.call('Emulation.setFocusEmulationEnabled',{enabled:true});
 const click=selector=>client.eval('document.querySelector('+JSON.stringify(selector)+').click()'),shot=async name=>{const r=await client.call('Page.captureScreenshot',{format:'png'});fs.writeFileSync(path.join(out,mode+'-'+name+'.png'),Buffer.from(r.data,'base64'));},value=async(selector,text)=>client.eval('(()=>{const e=document.querySelector('+JSON.stringify(selector)+');e.value='+JSON.stringify(text)+';e.dispatchEvent(new Event("change",{bubbles:true}));})()');
 await client.call('Page.navigate',{url:server.url+'/sessions'});await client.wait('document.querySelectorAll("#sessions .session-card").length===4');
 await check('dedicated session page shows four live connections and collapsed history',async()=>{assert.equal(await client.eval('document.getElementById("title").textContent'),'세션과 에이전트');assert.equal(await client.eval('document.getElementById("workflow-page").hidden'),true);assert.equal(await client.eval('document.getElementById("session-history").open'),false);assert.equal(await client.eval('document.querySelectorAll("#session-history-list .session-card").length'),0);await shot('desktop-sessions');});
 await check('only current node attempts are counted as live agents',async()=>{assert.equal(await client.eval('document.querySelectorAll("#sessions .agent-row[data-live=true]").length'),2);assert.ok((await client.eval('document.getElementById("session-summary").textContent')).includes('에이전트 2'));assert.ok((await client.eval('document.querySelector(".agent-row[data-live=true] small").textContent')).includes('응답 미확인'));});
 await check('waiting card names the blocking session and node',async()=>{const text=await client.eval('document.querySelector(".session-wait").textContent');assert.ok(text.includes('Claude 화면'));assert.ok(text.includes('frontend'));});
 await check('runtime and work filters intersect without changing other settings',async()=>{await value('#session-runtime-filter','codex');assert.equal(await client.eval('document.querySelectorAll("#sessions .session-card").length'),2);await value('#session-work-filter',work.work_id);assert.equal(await client.eval('document.querySelectorAll("#sessions .session-card").length'),1);await value('#session-runtime-filter','');await value('#session-work-filter','');});
 await check('attention filter finds dead controllers',async()=>{await value('#session-state-filter','attention');assert.equal(await client.eval('document.querySelectorAll("#sessions .session-card").length'),1);assert.equal(await client.eval('document.querySelector("#sessions .session-card").dataset.state'),'disconnected');await value('#session-state-filter','');});
 const selector='#sessions [data-session-id="'+a.session_id+'"]';
 await check('renaming survives live snapshot refresh while the form is open',async()=>{await click(selector+' .session-footer button');await client.wait('document.getElementById("session-action-dialog").open');await value('#session-action-value','Claude 로그인 UI');await client.eval('refresh()');assert.equal(await client.eval('document.getElementById("session-action-value").value'),'Claude 로그인 UI');await click('#session-action-save');await client.wait('!document.getElementById("session-action-dialog").open');assert.equal(repo.store.get('session/'+a.session_id).value.name,'Claude 로그인 UI');});
 await check('cooperative stop retains the running node until it finishes',async()=>{await client.eval('(()=>{const card=document.querySelector('+JSON.stringify(selector)+');[...card.querySelectorAll("button")].find(b=>b.textContent==="새 배정 중지").click()})()');await client.wait('document.querySelector('+JSON.stringify(selector)+').dataset.state==="stopping"');assert.equal(c.node(work.work_id,'frontend').run_id,ca.run_id);});
 await check('dead controller recovery exposes quarantined work in history',async()=>{await client.eval('[...document.querySelectorAll("#sessions button")].find(b=>b.textContent==="죽은 세션 복구").click()');await client.wait('document.getElementById("session-history").open && document.querySelectorAll("#session-history-list .session-card").length===2');assert.equal(c.node(orphan.work_id,'recover').status,'quarantined');});
 await check('quarantine release requires a reason and keeps old execution fenced',async()=>{await client.eval('[...document.querySelectorAll("#session-history-list button")].find(b=>b.textContent==="검토 후 다시 배정").click()');await client.wait('document.getElementById("session-action-dialog").open');await value('#session-action-value','프로세스 종료와 격리 작업 파일 확인');await click('#session-action-save');await client.wait('!document.getElementById("session-action-dialog").open');assert.equal(c.node(orphan.work_id,'recover').status,'pending');assert.throws(()=>c.heartbeat(dead),/SESSION_AUTH/);});
 for(const width of [1600,768,390])await check('session controls and cards fit '+width+'px',async()=>{await client.call('Emulation.setDeviceMetricsOverride',{width,height:1000,deviceScaleFactor:1,mobile:false});await sleep(80);assert.ok(await client.eval('document.documentElement.scrollWidth<=innerWidth+1'));const boxes=await client.eval('[...document.querySelectorAll("#sessions .session-card")].map(e=>({left:e.getBoundingClientRect().left,right:e.getBoundingClientRect().right}))');assert.ok(boxes.every(b=>b.left>=0&&b.right<=width));if(width===390)await shot('mobile-sessions');});
 await client.call('Emulation.setDeviceMetricsOverride',{width:1600,height:1100,deviceScaleFactor:1,mobile:false});await client.call('Page.navigate',{url:server.url+'/workflows?work='+work.work_id+'&session='+b.session_id});await client.wait('document.querySelectorAll(".node").length===2');
 await check('session focus highlights owned nodes and retains dependency context',async()=>{assert.equal(await client.eval('document.querySelectorAll(".node.session-owned-node").length'),1);assert.equal(await client.eval('document.querySelectorAll(".node.session-other-node").length'),1);assert.ok((await client.eval('document.querySelector(".node.session-owned-node .node-owner").textContent')).includes('Codex'));await client.eval('document.getElementById("graph").scrollIntoView({block:"center"})');await shot('owned-map');});
 await check('workflow offers an explicit additional session with runtime selection',async()=>{await click('.add-work-session');await client.wait('document.getElementById("session-action-dialog").open');assert.equal(await client.eval('document.getElementById("session-launch-label").hidden'),false);assert.equal(await client.eval('document.querySelectorAll("#session-launch-runtime option").length'),2);await click('#session-action-close');assert.equal(client.errors.length,0);});
 fs.writeFileSync(path.join(out,mode+'-sessions.json'),JSON.stringify({status:'passed',checks,mode,browser,at:new Date().toISOString()},null,2));console.log('결과: '+checks+' PASS / 0 FAIL');
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(async()=>{if(client){await client.call('Browser.close').catch(()=>{});client.close();}if(child&&child.exitCode===null)child.kill();if(c)for(const s of credentials){try{for(const n of c.snapshot().nodes.filter(n=>n.session_id===s.session_id&&['claimed','running','verifying'].includes(n.status)))c.failRun(s,n.work_id,n.node_id,n.run_id,n.epoch,'fixture cleanup');c.leave(s);}catch{}}await server?.close();repo?.store.close();});
