'use strict';
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict'),{spawn}=require('node:child_process');
const {CDP}=require('./test_ui_browser'),{repository,git}=require('../../.claude/hooks/_harness-store'),{Coordinator}=require('../../.claude/hooks/_coordinator'),managed=require('../../.claude/hooks/_managed-work'),{startServer}=require('../../.claude/hooks/_ui-server');
const sleep=ms=>new Promise(r=>setTimeout(r,ms)),root=fs.mkdtempSync(path.join(os.tmpdir(),'harness-component-browser-')),repoDir=path.join(root,'project'),out=process.env.HARNESS_BROWSER_EVIDENCE||path.join(root,'evidence'),mode=process.env.HARNESS_TEST_MODE||'headless';let repo,server,child,client,coordinator,credential,viewWork,claim,checks=0;
const check=async(name,fn)=>{await fn();checks++;console.log('PASS '+name);};
(async()=>{
 fs.mkdirSync(repoDir);fs.mkdirSync(out,{recursive:true});git(repoDir,['init','-q']);fs.cpSync(path.resolve(__dirname,'../../.claude/hooks'),path.join(repoDir,'.claude/hooks'),{recursive:true});for(const [f,t]of Object.entries({'value.txt':'before','prd.md':'# Test PRD','plan.md':'# Test plan'}))fs.writeFileSync(path.join(repoDir,f),t);git(repoDir,['add','.']);git(repoDir,['-c','user.name=Test','-c','user.email=test@example.invalid','commit','-qm','fixture']);
 repo=repository(repoDir);server=await startServer(repoDir,{context:repo});coordinator=new Coordinator(repo.store,{repo_id:repo.repo_id});credential=coordinator.join({runtime:'codex',worktree:repoDir});
 viewWork=coordinator.createWork({track:'C',title:'이동·줌 검증',nodes:[{id:'map-first',title:'현재 작업',files:['map-only.txt']},{id:'map-next',title:'다음 작업',files:['map-next.txt'],deps:['map-first']}]});coordinator.authorize(viewWork.work_id,{source:'user',reference:'browser view fixture'},viewWork.graph_hash);claim=coordinator.claim(credential,viewWork.work_id,'map-first');coordinator.start(credential,viewWork.work_id,'map-first',claim.run_id,claim.epoch);
 const other=coordinator.createWork({track:'B',title:'다른 보기',nodes:[{id:'other',files:['other.txt']}]});
 const browser=process.env.HARNESS_BROWSER||['C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe','C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe'].find(fs.existsSync);assert.ok(browser,'A real browser is required');
 const profile=path.join(root,'browser');fs.mkdirSync(profile);child=spawn(browser,['--remote-debugging-port=0','--user-data-dir='+profile,'--no-first-run','--no-default-browser-check','--disable-background-networking','--window-size=1600,1200',...(mode==='headless'?['--headless=new']:[]),'about:blank'],{windowsHide:mode==='headless',stdio:'ignore'});
 const portFile=path.join(profile,'DevToolsActivePort');for(let i=0;i<120&&!fs.existsSync(portFile);i++)await sleep(100);assert.ok(fs.existsSync(portFile));const port=Number(fs.readFileSync(portFile,'utf8').split('\n')[0]),targets=await(await fetch('http://127.0.0.1:'+port+'/json')).json();client=await CDP.connect(targets.find(t=>t.type==='page').webSocketDebuggerUrl);await client.call('Page.bringToFront');await client.call('Emulation.setFocusEmulationEnabled',{enabled:true});await client.call('Emulation.setDeviceMetricsOverride',{width:1600,height:1200,deviceScaleFactor:1,mobile:false});
 const click=selector=>client.eval('document.querySelector('+JSON.stringify(selector)+').click()');
 const reload=async()=>{await client.eval('window.reloadMarker=true');await client.call('Page.reload');await client.wait('!window.reloadMarker && document.querySelectorAll("[data-stage-library=workflow] .component-card").length===8');};
 const set=async(id,value)=>client.eval('(()=>{const e=document.getElementById('+JSON.stringify(id)+');e.value='+JSON.stringify(value)+';e.dispatchEvent(new Event("input",{bubbles:true}));e.dispatchEvent(new Event("change",{bubbles:true}));})()');
 const matrix=()=>client.eval('(()=>{const m=new DOMMatrix(getComputedStyle(document.querySelector(".graph-canvas")).transform);return {x:m.e,y:m.f,z:m.a}})()');
 const rect=selector=>client.eval('(()=>{const r=document.querySelector('+JSON.stringify(selector)+').getBoundingClientRect();return {x:r.x,y:r.y,width:r.width,height:r.height}})()');
 const mouse=(type,x,y,extra={})=>client.call('Input.dispatchMouseEvent',{type,x,y,...extra});
 const drag=async(start,end,button='left')=>{await mouse('mouseMoved',start.x,start.y);await mouse('mousePressed',start.x,start.y,{button,buttons:button==='middle'?4:1,clickCount:1});await sleep(50);await mouse('mouseMoved',end.x,end.y,{button,buttons:button==='middle'?4:1});await sleep(50);await mouse('mouseReleased',end.x,end.y,{button,clickCount:1});};
 async function nativeDrop(source,target){
  await client.eval('if(!document.getElementById("preset-editor").open)document.getElementById("edit-preset").click()');
  await client.eval('document.querySelector(".composer-grid").scrollIntoView({block:"center"})');
  for(const selector of [source,target])await client.eval('document.querySelector('+JSON.stringify(selector)+').scrollIntoView({block:"nearest",inline:"nearest"})');
  const a=await rect(source),b=await rect(target),from={x:a.x+a.width/2,y:a.y+a.height/2},to={x:b.x+b.width/2,y:b.y+b.height/2};
  for(const [selector,p]of [[source,from],[target,to]])assert.ok(await client.eval('(()=>{const e=document.querySelector('+JSON.stringify(selector)+'),h=document.elementFromPoint('+p.x+','+p.y+');return !!h&&(e===h||e.contains(h));})()'),'Drag endpoint must be visible: '+selector);
  await client.call('Input.setInterceptDrags',{enabled:true});let listener,timer;const intercepted=new Promise((resolve,reject)=>{timer=setTimeout(()=>reject(Error('NATIVE_DRAG_NOT_STARTED')),5000);listener=event=>{const message=JSON.parse(event.data);if(message.method==='Input.dragIntercepted'){clearTimeout(timer);resolve(message.params.data);}};client.ws.addEventListener('message',listener);});
  try{await mouse('mouseMoved',from.x,from.y);await mouse('mousePressed',from.x,from.y,{button:'left',buttons:1,clickCount:1});await sleep(100);for(let i=1;i<=10;i++){await mouse('mouseMoved',from.x+(to.x-from.x)*i/10,from.y+(to.y-from.y)*i/10,{button:'left',buttons:1});await sleep(30);}const data=await intercepted;assert.ok(data.items.some(i=>i.mimeType==='application/x-harness-component'));
   for(const type of ['dragEnter','dragOver','drop'])await client.call('Input.dispatchDragEvent',{type,x:to.x,y:to.y,data});await mouse('mouseReleased',to.x,to.y,{button:'left',clickCount:1});
  }finally{clearTimeout(timer);client.ws.removeEventListener('message',listener);await client.call('Input.setInterceptDrags',{enabled:false});}
 }
 await client.call('Page.navigate',{url:server.url+'/workflows?work='+viewWork.work_id});await client.wait('document.querySelectorAll(".node").length===2 && document.querySelectorAll("[data-stage-library=workflow] .component-card").length===8');
 await check('component library and independent execution map load',async()=>{assert.equal(await client.eval('document.querySelectorAll(".designer-node").length'),5);assert.equal(client.errors.length,0);});
 await client.eval('document.getElementById("graph").scrollIntoView({block:"center"})');
 await check('background drag pans the actual map and pauses following',async()=>{const r=await rect('#graph'),before=await matrix();await drag({x:r.x+15,y:r.y+15},{x:r.x+105,y:r.y+55});const after=await matrix();assert.ok(Math.abs(after.x-before.x-90)<1,JSON.stringify({before,after,r}));assert.ok(Math.abs(after.y-before.y-40)<1);assert.equal(await client.eval('document.getElementById("follow-active").checked'),false);});
 await check('wheel zoom keeps the world point under the cursor fixed',async()=>{const r=await rect('#graph'),p={x:r.x+r.width/2,y:r.y+r.height/2},before=await matrix();await mouse('mouseWheel',p.x,p.y,{deltaX:0,deltaY:-180});await sleep(100);const after=await matrix();assert.ok(after.z>before.z);assert.ok(Math.abs((p.x-r.x-1-before.x)/before.z-(p.x-r.x-1-after.x)/after.z)<1);assert.ok(Math.abs((p.y-r.y-1-before.y)/before.z-(p.y-r.y-1-after.y)/after.z)<1);});
 await check('pointer capture and view survive a live redraw during dragging',async()=>{const r=await rect('#graph'),before=await matrix();await mouse('mousePressed',r.x+15,r.y+15,{button:'left',buttons:1,clickCount:1});await mouse('mouseMoved',r.x+35,r.y+35,{buttons:1});await client.eval('window.canvasBefore=document.querySelector(".graph-canvas")');repo.store.transaction(tx=>tx.event('test.map_refresh',{}));await client.wait('document.querySelector(".graph-canvas")!==window.canvasBefore');await mouse('mouseMoved',r.x+75,r.y+65,{buttons:1});await mouse('mouseReleased',r.x+75,r.y+65,{button:'left',clickCount:1});const after=await matrix();assert.ok(Math.abs(after.x-before.x-60)<1);assert.ok(Math.abs(after.y-before.y-50)<1);assert.equal(after.z,before.z);});
 await check('reload and work switching restore independent pan zoom and follow state',async()=>{const before=await matrix();await reload();await client.wait('document.querySelectorAll(".node").length===2');assert.deepEqual(await matrix(),before);assert.equal(await client.eval('document.getElementById("follow-active").checked'),false);await set('work-select',other.work_id);await set('work-select',viewWork.work_id);assert.deepEqual(await matrix(),before);});
 await client.eval('document.getElementById("graph").scrollIntoView({block:"center"})');
 await check('zoom buttons range fit and keyboard are usable',async()=>{await click('#zoom-reset');assert.equal((await matrix()).z,1);await click('#zoom-in');assert.ok((await matrix()).z>1);await set('zoom-range','200');assert.equal((await matrix()).z,2);await set('zoom-range','25');assert.equal((await matrix()).z,.25);await click('#zoom-fit');assert.ok((await matrix()).z>=.25);await client.eval('document.getElementById("graph").focus()');const before=await matrix();await client.call('Input.dispatchKeyEvent',{type:'keyDown',key:'ArrowLeft',code:'ArrowLeft'});await client.call('Input.dispatchKeyEvent',{type:'keyUp',key:'ArrowLeft',code:'ArrowLeft'});assert.equal((await matrix()).x,before.x+40);});
 await check('middle mouse pans without selecting a node',async()=>{const r=await rect('#graph'),before=await matrix();await drag({x:r.x+20,y:r.y+20},{x:r.x+60,y:r.y+35},'middle');assert.ok(Math.abs((await matrix()).x-before.x-40)<1);assert.equal(await client.eval('document.querySelectorAll(".node.selected").length'),0);});
 await check('active-node focus preserves zoom and resumes following',async()=>{const before=await matrix();await click('#focus-active');assert.equal((await matrix()).z,before.z);assert.equal(await client.eval('document.getElementById("follow-active").checked'),true);assert.ok(await client.eval('!!document.querySelector(".node.active-node.selected")'));});
 let shot=await client.call('Page.captureScreenshot',{format:'png'});fs.writeFileSync(path.join(out,mode+'-map.png'),Buffer.from(shot.data,'base64'));
 const originalConfig=JSON.stringify(repo.store.get('models/config'));
 await click('#edit-preset');await click('[data-stage-library=workflow] [data-component=analysis] .component-actions button');await client.wait('document.getElementById("stage-dialog").open');
 await check('component dialog exposes both launcher profiles',async()=>{assert.equal(await client.eval('document.querySelectorAll("#stage-profiles .stage-profile").length'),2);await click('#stage-inherit');await set('stage-name','분석 부품 테스트');await set('stage-instructions','GUI_COMPONENT_FROZEN');});
 async function binding(runtime,provider,model,effort='high'){
  await client.eval('(()=>{const p=document.querySelector(".stage-profile[data-launcher='+runtime+']"),s=p.querySelectorAll("select");s[0].value='+JSON.stringify(provider)+';s[0].dispatchEvent(new Event("change"));if('+JSON.stringify(model)+'!==null){s[1].value="__custom";s[1].dispatchEvent(new Event("change"));const c=p.querySelector("input:not([type=checkbox])");c.value='+JSON.stringify(model)+';c.dispatchEvent(new Event("input"));s[2].value='+JSON.stringify(effort)+';s[2].dispatchEvent(new Event("change"));const q=p.querySelector("input[type=checkbox]");q.checked=false;q.dispatchEvent(new Event("change"));}})()');
 }
 await check('provider switches preserve Claude and Codex choices in each component',async()=>{await binding('claude','claude','sonnet-component','medium');await binding('claude','codex','codex-remembered');await binding('claude','claude',null);assert.equal(await client.eval('document.querySelector(".stage-profile[data-launcher=claude]").querySelectorAll("select")[1].value'),'sonnet-component');await binding('codex','codex','codex-component');await click('#stage-save');await client.wait('document.getElementById("stage-status").textContent.includes("저장했습니다")');assert.equal(JSON.stringify(repo.store.get('models/config')),originalConfig);});
 await click('#stage-close');await reload();await client.wait('document.querySelector("[data-component=analysis]")?.textContent.includes("분석 부품 테스트")');
 await check('saved component values reload through the shared settings endpoint',async()=>{await click('[data-stage-library=workflow] [data-component=analysis] .component-actions button');await client.wait('document.getElementById("stage-dialog").open');assert.equal(await client.eval('document.querySelector(".stage-profile[data-launcher=codex]").querySelectorAll("select")[1].value'),'codex-component');assert.equal(await client.eval('document.getElementById("stage-instructions").value'),'GUI_COMPONENT_FROZEN');await click('#stage-close');});
 await check('native drag onto a builtin creates a copy without modifying it',async()=>{await nativeDrop('[data-stage-library=workflow] [data-component=analysis] strong','#designer-viewport');assert.equal(await client.eval('presetDraft.builtin'),false);assert.equal(await client.eval('presetDraft.steps.length'),6);assert.equal((await(await fetch(server.url+'/api/workflow-presets')).json()).find(p=>p.id==='standard').steps.length,5);});
 await click('#designer-discard');await click('#designer-close');await click('#empty-workflow');
 await check('native drag builds an empty workflow from a reusable component',async()=>{await nativeDrop('[data-stage-library=workflow] [data-component=analysis] strong','#designer-viewport');assert.equal(await client.eval('presetDraft.steps.length'),1);assert.deepEqual(await client.eval('presetDraft.steps[0].deps'),[]);});
 let first=await client.eval('presetDraft.steps[0].id');
 await check('the same component can be reused with sequential dependencies',async()=>{await nativeDrop('[data-stage-library=workflow] [data-component=analysis] strong','#designer-viewport');assert.equal(await client.eval('presetDraft.steps.length'),2);const next=await client.eval('presetDraft.steps[1].id');await click('[data-preset-node="'+first+'"] [data-port=out]');await click('[data-preset-node="'+next+'"] [data-port=in]');assert.deepEqual(await client.eval('presetDraft.steps[1].deps'),[first]);assert.notEqual(await client.eval('presetDraft.steps[1].id'),first);});
 const second=await client.eval('presetDraft.steps[1].id');
 await check('parallel component drops update dependencies and the preview',async()=>{await nativeDrop('[data-stage-library=workflow] [data-component=review] strong','#designer-viewport');const steps=await client.eval('presetDraft.steps'),parallel=steps.find(s=>s.component_id==='review');await click('[data-preset-node="'+parallel.id+'"] [data-port=out]');await click('[data-preset-node="'+second+'"] [data-port=in]');steps.find(s=>s.id===second).deps=await client.eval('presetDraft.steps.find(s=>s.id==='+JSON.stringify(second)+').deps');assert.deepEqual(parallel.deps,[]);assert.deepEqual(new Set(steps.find(s=>s.id===second).deps),new Set([first,parallel.id]));assert.equal(await client.eval('document.querySelectorAll(".designer-node").length'),3);});
 await set('preset-name','브라우저 부품 흐름');await click('#save-preset');await client.wait('document.getElementById("alert").textContent.includes("프리셋을 저장했습니다")');const presetId=await client.eval('presetDraft.id');
 await click('#designer-close');
 await check('GUI task registration freezes the component definitions',async()=>{await set('launch-runtime','codex');await click('#new-work');await set('work-title','GUI 부품 실행 검증');await set('work-prd','prd.md');await set('work-plan','plan.md');await client.eval('('+function(){for(const [i,c]of [...document.querySelectorAll('#work-tasks .task-card')].entries()){c.querySelector('[data-field=prompt]').value='Write component result';c.querySelector('[data-field=files]').value='result-'+i+'.txt';c.querySelector('[data-field=automated]').value=JSON.stringify(['node','-e','require("assert").equal(require("fs").readFileSync("result-'+i+'.txt","utf8"),"done");console.log("1 passed")']);}}.toString()+')()');await click('#work-builder button[type=submit]');await client.wait('document.getElementById("alert").textContent.includes("작업을 등록했습니다")');});
 const work=repo.store.list('work/').map(r=>r.value).find(w=>w.title==='GUI 부품 실행 검증');assert.ok(work);assert.equal(work.workflow.preset_id,presetId);
 await check('actual managed execution receives the GUI model and frozen instructions',async()=>{let componentCalls=0;const result=await managed.run(repo,work.work_id,{runtime:'codex',onNotice:()=>{},modelRunner:async(profile,prompt)=>{const packet=JSON.parse(prompt.slice(prompt.indexOf('Context:\n')+9).split('\nPrevious verification failed;')[0]);if(packet.component.id==='analysis'){componentCalls++;assert.equal(profile.runtime,'codex');assert.equal(profile.model,'codex-component');assert.equal(packet.component.instructions,'GUI_COMPONENT_FROZEN');}return {text:JSON.stringify({summary:'browser configured component',files:[{path:packet.files[0].path,content:'done'}]}),model:{status:'verified',observed:['fixture']}};}});assert.equal(result.status,'verified');assert.equal(componentCalls,2);});
 await client.wait('document.getElementById("work-summary").textContent.includes("검증 완료")');await click('.node');await client.wait('document.getElementById("node-detail").textContent.includes("단계 부품")');
 await check('component settings are also available on the model page',async()=>{await client.call('Page.navigate',{url:server.url+'/models'});await client.wait('document.querySelectorAll("[data-stage-library=models] .component-card").length===8');assert.ok((await client.eval('document.querySelector("[data-stage-library=models] [data-component=analysis]").textContent')).includes('codex-component'));assert.equal(client.errors.length,0);});
 shot=await client.call('Page.captureScreenshot',{format:'png'});fs.writeFileSync(path.join(out,mode+'-components.png'),Buffer.from(shot.data,'base64'));fs.writeFileSync(path.join(out,mode+'-component-evidence.json'),JSON.stringify({mode,checks,status:'passed',browser,at:new Date().toISOString()},null,2));console.log('결과: '+checks+' PASS / 0 FAIL');
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(async()=>{if(client){await client.call('Browser.close').catch(()=>{});client.close();}if(child&&child.exitCode===null)child.kill();if(credential)try{coordinator.failRun(credential,viewWork.work_id,'map-first',claim.run_id,claim.epoch,'fixture cleanup');coordinator.leave(credential);}catch{}await server?.close();repo?.store.close();});
