'use strict';
const fs=require('fs'),path=require('path'),os=require('os'),assert=require('assert/strict'),{spawn}=require('child_process'),{CDP}=require('./test_ui_browser'),{repository,git}=require('../../.claude/hooks/_harness-store'),{Coordinator}=require('../../.claude/hooks/_coordinator'),{startServer}=require('../../.claude/hooks/_ui-server');
const root=fs.mkdtempSync(path.join(os.tmpdir(),'harness-theme-browser-')),project=path.join(root,'project'),profile=path.join(root,'browser'),mode=process.env.HARNESS_TEST_MODE||'headless',out=process.env.HARNESS_BROWSER_EVIDENCE||path.join(root,'evidence'),sleep=ms=>new Promise(r=>setTimeout(r,ms));let repo,server,c,credential,work,claim,client,child,checks=0;
async function check(name,fn){await fn();checks++;console.log('PASS '+name);}
(async()=>{
 fs.mkdirSync(project);fs.mkdirSync(profile);fs.mkdirSync(out,{recursive:true});git(project,['init','-q']);repo=repository(project);server=await startServer(project,{context:repo});c=new Coordinator(repo.store,{repo_id:repo.repo_id});credential=c.join({runtime:'codex',worktree:project});
 work=c.createWork({track:'C',title:'대시보드 디자인 검증',nodes:[{id:'analysis',title:'요구사항 분석',files:['analysis.txt']},{id:'frontend',title:'화면 구현',deps:['analysis'],files:['frontend.txt']},{id:'backend',title:'실행 연결',deps:['analysis'],files:['backend.txt']},{id:'verify',title:'통합 검증',deps:['frontend','backend'],files:['test.txt']}]});c.authorize(work.work_id,{source:'user',reference:'theme browser fixture'},work.graph_hash);claim=c.claim(credential,work.work_id,'analysis');c.start(credential,work.work_id,'analysis',claim.run_id,claim.epoch);
 const browser=process.env.HARNESS_BROWSER||['C:/Program Files/Google/Chrome/Application/chrome.exe','C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'].find(fs.existsSync);assert.ok(browser);child=spawn(browser,['--remote-debugging-port=0','--user-data-dir='+profile,'--window-size=1600,1100','--no-first-run','--no-default-browser-check',...(mode==='headless'?['--headless=new']:[]),'about:blank'],{windowsHide:mode==='headless',stdio:'ignore'});
 const portFile=path.join(profile,'DevToolsActivePort');for(let i=0;i<120&&!fs.existsSync(portFile);i++)await sleep(100);const port=Number(fs.readFileSync(portFile,'utf8').split('\n')[0]),tabs=await(await fetch('http://127.0.0.1:'+port+'/json')).json();client=await CDP.connect(tabs.find(t=>t.type==='page').webSocketDebuggerUrl);await client.call('Page.bringToFront');await client.call('Emulation.setFocusEmulationEnabled',{enabled:true});
 const size=async(width,height)=>{await client.call('Emulation.setDeviceMetricsOverride',{width,height,deviceScaleFactor:1,mobile:false});await sleep(80);},click=selector=>client.eval('document.querySelector('+JSON.stringify(selector)+').click()'),shot=async name=>{const r=await client.call('Page.captureScreenshot',{format:'png'});fs.writeFileSync(path.join(out,mode+'-'+name+'.png'),Buffer.from(r.data,'base64'));};
 async function readable(selectors){
  const rows=await client.eval('('+function(list){function rgb(s){return s.match(/[\d.]+/g)?.map(Number)||[];}function lum(c){const v=c.slice(0,3).map(x=>{x/=255;return x<=.04045?x/12.92:((x+.055)/1.055)**2.4;});return v[0]*.2126+v[1]*.7152+v[2]*.0722;}return list.map(selector=>{const e=document.querySelector(selector),style=getComputedStyle(e);let parent=e,bg;while(parent){bg=rgb(getComputedStyle(parent).backgroundColor);if(bg.length===3||bg[3]===1)break;parent=parent.parentElement;}const a=lum(rgb(style.color)),b=lum(bg);return {selector,ratio:(Math.max(a,b)+.05)/(Math.min(a,b)+.05)};});}.toString()+')('+JSON.stringify(selectors)+')');for(const row of rows)assert.ok(row.ratio>=4.5,JSON.stringify(row));
 }
 await size(1600,1100);await client.call('Page.navigate',{url:server.url+'/workflows?work='+work.work_id});await client.wait('document.querySelectorAll(".node").length===4 && document.querySelectorAll("[data-stage-library=workflow] .component-card").length===8');
 await check('dark desktop dashboard has readable content and live metrics',async()=>{assert.equal(await client.eval('getComputedStyle(document.documentElement).colorScheme'),'dark');assert.equal(await client.eval('document.getElementById("metric-running").textContent'),'1');assert.equal(await client.eval('document.querySelectorAll(".metrics svg").length'),4);await readable(['#title','#subtitle','.metrics article>span','nav a.active','.component-card strong','.component-card small','.component-description','.designer-hint']);await shot('desktop');});
 await check('toolbar inputs and action buttons share one bottom edge',async()=>{const boxes=await client.eval('[...document.querySelectorAll(".workflow-actions select,.workflow-actions>button")].map(e=>({bottom:e.getBoundingClientRect().bottom,height:e.getBoundingClientRect().height}))');assert.ok(Math.max(...boxes.map(x=>x.bottom))-Math.min(...boxes.map(x=>x.bottom))<=1,JSON.stringify(boxes));assert.ok(boxes.every(x=>Math.abs(x.height-40)<=1));});
 await check('advanced step fields form complete rows without overflowing their card',async()=>{await click('#edit-preset');const box=await client.eval('(()=>{const e=document.querySelector(".step-fields"),r=e.getBoundingClientRect();return {left:r.left,right:r.right,fields:[...e.querySelectorAll("input,select,button")].map(f=>({left:f.getBoundingClientRect().left,right:f.getBoundingClientRect().right}))}})()');assert.ok(box.fields.every(f=>f.left>=box.left&&f.right<=box.right),JSON.stringify(box));assert.ok(await client.eval('document.querySelector(".designer-footer").getBoundingClientRect().bottom<=innerHeight'));await click('#designer-close');});
 await check('active graph and status text remain readable on the dark canvas',async()=>{await client.eval('document.getElementById("graph").scrollIntoView({block:"center"})');assert.equal(await client.eval('document.querySelectorAll(".node.active-node").length'),1);await readable(['.node.active-node strong','.node.active-node small','.node.active-node .status']);await shot('graph');});
 await check('keyboard focus and reduced motion remain available',async()=>{await client.eval('document.getElementById("zoom-fit").focus()');await client.call('Input.dispatchKeyEvent',{type:'keyDown',key:'Tab',code:'Tab'});await client.call('Input.dispatchKeyEvent',{type:'keyUp',key:'Tab',code:'Tab'});assert.equal(await client.eval('getComputedStyle(document.activeElement).outlineStyle'),'solid');await client.call('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'reduce'}]});assert.equal(await client.eval('getComputedStyle(document.querySelector(".node.active-node")).animationName'),'none');});
 await click('#edit-preset');await click('[data-stage-library=workflow] [data-component=analysis] .component-actions button');await client.wait('document.getElementById("stage-dialog").open');
 await check('both model profiles and disabled inherited values are legible',async()=>{assert.equal(await client.eval('document.querySelectorAll("#stage-profiles .stage-profile").length'),2);await readable(['#stage-dialog-title','#stage-name','.stage-profile h3','.stage-profile select:disabled','#stage-status']);await shot('model-dialog');});await click('#stage-close');
 await click('[data-stage-library=workflow] [data-component=analysis] .component-actions button');await client.wait('document.getElementById("stage-dialog").open');
 await check('dialog name and role controls align and checkbox labels remain horizontal',async()=>{const pos=await client.eval('({a:document.getElementById("stage-name").getBoundingClientRect().top,b:document.querySelector("#stage-role-control select").getBoundingClientRect().top,checkbox:getComputedStyle(document.querySelector(".stage-profile label:has(input[type=checkbox])")).flexDirection})');assert.ok(Math.abs(pos.a-pos.b)<=1,JSON.stringify(pos));assert.equal(pos.checkbox,'row-reverse');});await click('#stage-close');
 await click('#designer-close');
 for(const width of [768,390,360]){
  await check('workflow controls fit '+width+'px without page overflow',async()=>{await size(width,900);await client.eval('scrollTo(0,0)');const layout=await client.eval('({width:innerWidth,scroll:document.documentElement.scrollWidth})');assert.ok(layout.scroll<=layout.width+1,JSON.stringify(layout));assert.ok(await client.eval('document.getElementById("new-work").getBoundingClientRect().right<=innerWidth'));if(width===390)await shot('mobile-workflow');});
 }
 await click('[data-stage-library=workflow] [data-component=analysis] .component-actions button');await client.wait('document.getElementById("stage-dialog").open');
 await check('mobile model dialog stacks profiles and keeps actions reachable',async()=>{const box=await client.eval('(()=>{const d=document.getElementById("stage-dialog"),r=d.getBoundingClientRect(),a=document.querySelectorAll(".stage-profile");return {left:r.left,right:r.right,width:innerWidth,overflow:d.scrollWidth>d.clientWidth+1,first:a[0].getBoundingClientRect().top,second:a[1].getBoundingClientRect().top}})()');assert.ok(box.left>=0&&box.right<=box.width&&!box.overflow,JSON.stringify(box));assert.ok(box.second>box.first);await client.eval('document.getElementById("stage-save").scrollIntoView({block:"nearest"})');assert.ok(await client.eval('document.getElementById("stage-save").getBoundingClientRect().bottom<=innerHeight'));await shot('mobile-dialog');});await click('#stage-close');
 await click('#designer-close');await client.call('Page.navigate',{url:server.url+'/models'});await client.wait('document.querySelectorAll("[data-stage-library=models] .component-card").length===8');
 await check('model settings fit mobile and desktop including advanced role controls',async()=>{assert.ok(await client.eval('document.documentElement.scrollWidth<=innerWidth+1'));await click('#legacy-role-config>summary');assert.ok(await client.eval('document.documentElement.scrollWidth<=innerWidth+1'));await shot('mobile-models');await size(1600,1100);await client.eval('scrollTo(0,0)');await readable(['#models-page h2','.connection-card label','.model-stage-library .component-card small']);await shot('models');assert.equal(client.errors.length,0);});
 await check('component model rows and settings buttons align across the first card row',async()=>{const rows=await client.eval('[...document.querySelectorAll("[data-stage-library=models] .component-card")].slice(0,4).map(e=>({model:e.querySelectorAll("small")[0].getBoundingClientRect().top,button:e.querySelector("button").getBoundingClientRect().bottom}))');for(const key of ['model','button'])assert.ok(Math.max(...rows.map(r=>r[key]))-Math.min(...rows.map(r=>r[key]))<=1,JSON.stringify(rows));assert.ok(await client.eval('[...document.querySelectorAll(".preset-buttons>[data-preset]")].every(e=>getComputedStyle(e).display==="none")'));});
 await check('decorative role icons remain inside cards and retain text labels',async()=>{const icon=await client.eval('(()=>{const e=document.querySelector("[data-stage-library=models] [data-component=analysis]"),p=getComputedStyle(e,"::after");return {mask:p.maskImage,size:p.width,name:e.getAttribute("aria-label"),label:e.querySelector("strong").textContent}})()');assert.ok(icon.mask.startsWith('url('));assert.equal(icon.size,'19px');assert.ok(icon.name.includes(icon.label));});
 fs.writeFileSync(path.join(out,mode+'-theme-evidence.json'),JSON.stringify({status:'passed',checks,mode,browser,at:new Date().toISOString()},null,2));console.log('결과: '+checks+' PASS / 0 FAIL');
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(async()=>{if(client){await client.call('Browser.close').catch(()=>{});client.close();}if(child&&child.exitCode===null)child.kill();if(credential)try{c.failRun(credential,work.work_id,'analysis',claim.run_id,claim.epoch,'browser fixture cleanup');c.leave(credential);}catch{}await server?.close();repo?.store.close();});
