'use strict';
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),{spawn}=require('node:child_process'),assert=require('node:assert/strict');
const {repository,git}=require('../../.claude/hooks/_harness-store'),managed=require('../../.claude/hooks/_managed-work');
if(process.argv[2]==='worker'){
 const repo=repository(process.argv[3]);managed.run(repo,process.argv[4],{runtime:process.argv[5],max_wait_ms:180000,jobs:1,onNotice:line=>console.log(line)}).then(r=>{console.log(JSON.stringify(r));repo.store.close();}).catch(e=>{console.error(e.message);repo.store.close();process.exitCode=1;});
}else if(process.argv.includes('--ui')){
 browserSessions().catch(e=>{console.error(e);process.exitCode=1;});
}else{
 (async()=>{
  if(!process.argv.includes('--live'))throw Error('Pass --live explicitly; this integration test makes paid/authenticated model calls.');
  const dir=fs.mkdtempSync(path.join(os.tmpdir(),'harness-v14-live-'));git(dir,['init']);fs.writeFileSync(path.join(dir,'prd.md'),'# Two independent runtime checks\n');fs.writeFileSync(path.join(dir,'plan.md'),'# Parallel Claude and Codex nodes\n');git(dir,['add','.']);git(dir,['-c','user.name=Harness Test','-c','user.email=harness@example.invalid','commit','-m','fixture']);
  const repo=repository(dir),spec={title:'실제 Claude + Codex 동시 실행 검증',track:'C',prd:'prd.md',plan:'plan.md',nodes:['claude','codex'].map(runtime=>({id:runtime,files:[runtime+'.txt'],prompt:'Create '+runtime+'.txt with exactly '+runtime.toUpperCase()+'_OK followed by one newline. Return the required files JSON only.',model:{runtime,model:runtime==='claude'?'sonnet':'current',effort:runtime==='claude'?'low':'default',require_model:runtime==='claude'},max_attempts:1,tests:[{mode:'automated',format:'json',command:[process.execPath,'-e',"const fs=require('fs'),assert=require('assert');assert.equal(fs.readFileSync('"+runtime+".txt','utf8'),'"+runtime.toUpperCase()+"_OK\\n');console.log(JSON.stringify({status:'passed',checks:1}));"]}]}))};
  const work=managed.create(repo,spec,'user explicitly requested actual v14 implementation and multi-session validation');
  function worker(runtime){return new Promise((resolve,reject)=>{const c=spawn(process.execPath,[__filename,'worker',dir,work.work_id,runtime],{windowsHide:true,stdio:['ignore','pipe','pipe']});let out='',err='';c.stdout.on('data',b=>out+=b);c.stderr.on('data',b=>err+=b);c.on('error',reject);c.on('close',code=>resolve({runtime,code,out,err}));});}
  const results=await Promise.all([worker('claude'),worker('codex')]);
  const nodes=work.nodes.map(id=>repo.store.get('node/'+work.work_id+'/'+id).value),events=repo.store.events(0,10000);
  const evidence={fixture:dir,work_id:work.work_id,results,nodes:nodes.map(n=>({node_id:n.node_id,status:n.status,session_id:n.session_id,provenance:n.provenance,candidate:n.candidate,evidence:n.evidence})),events};
  const out=process.env.HARNESS_LIVE_EVIDENCE||path.join(dir,'live-evidence.json');fs.writeFileSync(out,JSON.stringify(evidence,null,2));repo.store.close();
  assert.ok(results.every(r=>r.code===0),JSON.stringify(results));assert.ok(nodes.every(n=>n.status==='verified'));assert.equal(new Set(nodes.map(n=>n.session_id)).size,2,'two independent session owners must execute');
  assert.equal(nodes.find(n=>n.node_id==='claude').provenance.status,'verified');
  console.log(JSON.stringify({work_id:work.work_id,models:nodes.map(n=>({node:n.node_id,...n.provenance})),evidence:out}));console.log('결과: 4 PASS / 0 FAIL');
 })().catch(e=>{console.error(e);process.exitCode=1;});
}

async function browserSessions(){
 const {CDP}=require('./test_ui_browser'),{startServer}=require('../../.claude/hooks/_ui-server'),{Coordinator}=require('../../.claude/hooks/_coordinator');
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'harness-two-window-')),root=path.join(dir,'project'),profile=path.join(dir,'chrome'),release=path.join(dir,'release'),mode=process.env.HARNESS_TEST_MODE||'headless',out=process.env.HARNESS_BROWSER_EVIDENCE||dir;fs.mkdirSync(root);fs.mkdirSync(profile);fs.mkdirSync(out,{recursive:true});git(root,['init','-q']);for(const f of ['prd.md','plan.md'])fs.writeFileSync(path.join(root,f),'# Two-window test');git(root,['add','.']);git(root,['-c','user.name=Harness','-c','user.email=harness@test','commit','-qm','fixture']);
 const repo=repository(root),c=new Coordinator(repo.store,{repo_id:repo.repo_id}),clients=[];let server,child,checks=0;const sleep=ms=>new Promise(r=>setTimeout(r,ms));
 async function until(fn){const start=Date.now();while(!fn()){if(Date.now()-start>60000)throw Error('TWO_WINDOW_TIMEOUT');await sleep(100);}}
 async function check(name,fn){await fn();checks++;console.log('PASS '+name);}
 try{
  const work=managed.create(repo,{title:'Two real dashboard windows',track:'C',max_parallel:2,launch_runtime:'codex',prd:'prd.md',plan:'plan.md',nodes:['A','B','C','D'].map(id=>({id,files:[id+'.txt'],executor:'command',command:[process.execPath,'-e',"const fs=require('fs');const interval=setInterval(()=>{if(fs.existsSync("+JSON.stringify(release)+")){fs.writeFileSync('"+id+".txt','done');clearInterval(interval);}},100);setTimeout(()=>{throw Error('release timeout')},60000).unref();"],tests:[{mode:'automated',format:'json',command:[process.execPath,'-e',"require('assert').equal(require('fs').readFileSync('"+id+".txt','utf8'),'done');console.log(JSON.stringify({status:'passed',checks:1}))"]}]}))},'Two browser windows launch authorized command fixtures');
  server=await startServer(root,{context:repo,...(process.env.HARNESS_SESSION_UI_SOURCE?{assets:require(path.join(process.env.HARNESS_SESSION_UI_SOURCE,'.claude/hooks/_ui-assets'))}:{})});
  const browser=process.env.HARNESS_BROWSER||['C:/Program Files/Google/Chrome/Application/chrome.exe','C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'].find(fs.existsSync);assert.ok(browser);child=spawn(browser,['--remote-debugging-port=0','--user-data-dir='+profile,'--window-size=1500,1000','--no-first-run','--no-default-browser-check',...(mode==='headless'?['--headless=new']:[]),'about:blank'],{windowsHide:mode==='headless',stdio:'ignore'});
  const portFile=path.join(profile,'DevToolsActivePort');await until(()=>fs.existsSync(portFile));const port=Number(fs.readFileSync(portFile,'utf8').split('\n')[0]);let tabs=await(await fetch('http://127.0.0.1:'+port+'/json')).json();const one=await CDP.connect(tabs.find(t=>t.type==='page').webSocketDebuggerUrl);clients.push(one);const target=await one.call('Target.createTarget',{url:'about:blank',newWindow:true});tabs=await(await fetch('http://127.0.0.1:'+port+'/json')).json();const two=await CDP.connect(tabs.find(t=>t.id===target.targetId).webSocketDebuggerUrl);clients.push(two);
  for(const client of clients){await client.call('Page.navigate',{url:server.url+'/workflows?work='+work.work_id});await client.wait('document.querySelector(".add-work-session")');}
  async function launch(client,runtime,name){await client.call('Page.bringToFront');await client.eval('document.querySelector(".add-work-session").click()');await client.wait('document.getElementById("session-action-dialog").open');await client.eval('document.getElementById("session-launch-runtime").value='+JSON.stringify(runtime)+';document.getElementById("session-action-value").value='+JSON.stringify(name)+';document.getElementById("session-action-save").click()');await client.wait('!document.getElementById("session-action-dialog").open');}
  await check('two dashboard windows launch separate Claude and Codex sessions',async()=>{await launch(one,'claude','Claude 창');await launch(two,'codex','Codex 창');await until(()=>c.snapshot().sessions.filter(s=>s.status==='active').length===2);assert.deepEqual(new Set(c.snapshot().sessions.map(s=>s.runtime)),new Set(['claude','codex']));});
  await check('both windows observe the same ownership and live command agents',async()=>{for(const client of clients){await client.wait('document.querySelectorAll("#sessions .session-card").length===2');assert.ok(await client.eval('document.querySelectorAll(".node.active-node").length>0'));}await until(()=>repo.store.list('agent/').some(r=>r.value.last_event==='command.started'));assert.ok(repo.store.list('agent/').every(r=>r.value.executor==='command'));});
  const selected=c.snapshot().sessions.find(s=>s.runtime==='claude');
  await check('stopping one window drains its nodes while the other completes the graph',async()=>{await one.eval('[...document.querySelectorAll('+JSON.stringify('#sessions [data-session-id="'+selected.session_id+'"] button')+')].find(b=>b.textContent==="새 배정 중지").click()');await until(()=>repo.store.get('session/'+selected.session_id).value.stop_requested_at);fs.writeFileSync(release,'go');await until(()=>c.snapshot().nodes.every(n=>n.status==='verified'));await until(()=>c.snapshot().sessions.every(s=>s.status==='closed'));assert.equal(new Set(c.snapshot().nodes.map(n=>n.session_id)).size,2);assert.ok(c.snapshot().nodes.every(n=>n.attempts===1));});
  await check('both dashboards move closed sessions into history without browser errors',async()=>{for(let i=0;i<clients.length;i++){const client=clients[i];await client.wait('document.querySelectorAll("#sessions .session-card").length===0');await client.eval('document.getElementById("session-history").open=true;document.getElementById("session-panel").scrollIntoView({block:"start"})');await client.wait('document.querySelectorAll("#session-history-list .session-card").length===2');assert.equal(client.errors.length,0);const shot=await client.call('Page.captureScreenshot',{format:'png'});fs.writeFileSync(path.join(out,mode+'-window-'+i+'.png'),Buffer.from(shot.data,'base64'));}});
  const evidence={status:'passed',checks,mode,sessions:c.snapshot().sessions.map(s=>({name:s.name,runtime:s.runtime,status:s.status})),nodes:c.snapshot().nodes.map(n=>({id:n.node_id,owner:n.session_id,status:n.status})),at:new Date().toISOString()};fs.writeFileSync(path.join(out,mode+'-two-windows.json'),JSON.stringify(evidence,null,2));console.log('결과: '+checks+' PASS / 0 FAIL');
 }finally{fs.writeFileSync(release,'cleanup');if(clients[0])await clients[0].call('Browser.close').catch(()=>{});for(const client of clients)client.close();if(child&&child.exitCode===null)child.kill();await server?.close();repo.store.close();}
}
