<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <!-- DI Container -->
    <PackageReference Include="Autofac" Version="8.3.0" />

    <!-- ORM -->
    <PackageReference Include="Dapper" Version="2.1.66" />

    <!-- Database Driver -->
    <PackageReference Include="MySql.Data" Version="9.3.0" />

    <!-- MVVM Framework -->
    <PackageReference Include="Caliburn.Micro" Version="4.0.230" />

    <!-- MaterialDesign UI -->
    <PackageReference Include="MaterialDesignThemes" Version="5.2.1" />
    <PackageReference Include="MaterialDesignColors" Version="5.2.1" />

    <!-- JSON -->
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />

	<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.0" />
	<PackageReference Include="xunit" Version="2.9.3" />
	<PackageReference Include="xunit.runner.visualstudio" Version="3.1.0">
		<PrivateAssets>all</PrivateAssets>
		<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	</PackageReference>
  </ItemGroup>

  <ItemGroup>
    <!-- Project References -->
    <ProjectReference Include="..\Ironwall.Dotnet.Libraries.Base\Ironwall.Dotnet.Libraries.Base.csproj" />
    <ProjectReference Include="..\Ironwall.Dotnet.Libraries.ViewModel\Ironwall.Dotnet.Libraries.ViewModel.csproj" />
    <ProjectReference Include="..\Ironwall.Dotnet.Libraries.Utils\Ironwall.Dotnet.Libraries.Utils.csproj" />
    <ProjectReference Include="..\Ironwall.Dotnet.Monitoring.Models\Ironwall.Dotnet.Monitoring.Models.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Tests\" />
  </ItemGroup>

</Project>
