<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\Images\Surveillance_Unavailable.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="LibVLCSharp" Version="3.9.4" />
    <PackageReference Include="LibVLCSharp.WPF" Version="3.9.4" />
    <PackageReference Include="Polly" Version="8.6.3" />
    <PackageReference Include="VideoLAN.LibVLC.Windows" Version="3.0.21" />
  
	<!-- Caliburn.Micro (호스트 앱 라이브러리 버전 정합) -->
    <PackageReference Include="Caliburn.Micro" Version="4.0.230" />

    <!-- Autofac (호스트 앱 라이브러리 버전 정합) -->
    <PackageReference Include="Autofac" Version="8.3.0" />

    <!-- MaterialDesignThemes -->
    <PackageReference Include="MaterialDesignThemes" Version="5.2.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ironwall.Dotnet.Libraries.Base\Ironwall.Dotnet.Libraries.Base.csproj" />
    <ProjectReference Include="..\Ironwall.Dotnet.Libraries.Streaming.Base\Ironwall.Dotnet.Libraries.Streaming.Base.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\Images\Surveillance_Unavailable.png" />
  </ItemGroup>

</Project>
