'use strict';
const fs=require('fs'),path=require('path'),os=require('os'),assert=require('assert/strict'),{execFileSync}=require('child_process');
const {repository}=require('../../.claude/hooks/_harness-store'),{ModelConfig}=require('../../.claude/hooks/_model-config'),{WorkflowPresets}=require('../../.claude/hooks/_workflow-presets'),{SkillRegistry}=require('../../.claude/hooks/_skill-registry');
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'workflow-config-'));execFileSync('git',['init','-q'],{cwd:dir,windowsHide:true});
const repo=repository(dir),models=new ModelConfig(repo.store),presets=new WorkflowPresets(repo),skills=new SkillRegistry(repo);let checks=0;
function check(name,fn){fn();checks++;console.log('PASS '+name);}
try{
 check('Claude and Codex have independent default planning and implementation bindings',()=>{assert.equal(models.resolve({role:'planning',currentRuntime:'claude'}).model,'opus');assert.equal(models.resolve({role:'planning',currentRuntime:'codex'}).runtime,'codex');assert.equal(models.resolve({role:'documentation',currentRuntime:'codex'}).model,'sonnet');});
 check('saving one launcher leaves the other unchanged and records the actor',()=>{const old=models.read(),codex=JSON.stringify(old.value.launchers.codex);old.value.launchers.claude.roles.planning.model='sonnet';models.save(old.value,old.version,'one',{source:'user',runtime:'ui',session_id:'browser-fixture',reason:'planning preference'});assert.equal(JSON.stringify(models.read().value.launchers.codex),codex);assert.equal(models.history()[0].actor.source,'user');});
 const common=presets.get('standard');common.id='custom';common.name='내 개발 흐름';
 const saved=presets.save(common,0,{source:'user',runtime:'ui',reason:'fixture'});
 check('four built-in presets and a saved custom preset are listed',()=>assert.equal(presets.list().length,5));
 check('default presets cannot be overwritten and stale editors cannot overwrite newer versions',()=>{assert.throws(()=>presets.save(presets.get('standard'),0),/BUILTIN/);assert.throws(()=>presets.save(saved,0),/VERSION_CONFLICT/);});
 const separate=presets.get('custom');separate.variants.codex.inherit_common=false;separate.variants.codex.steps=JSON.parse(JSON.stringify(separate.steps));separate.variants.codex.steps[0].title='Codex 분석';separate.variants.codex.models.analysis={runtime:'codex',model:'codex-test-model',effort:'high',require_model:false};presets.save(separate,1);
 check('detached Codex steps survive changes to the common workflow',()=>{const p=presets.get('custom');p.steps[0].title='공통 분석 변경';presets.save(p,2);assert.equal(presets.freeze('custom','codex').steps[0].title,'Codex 분석');assert.equal(presets.freeze('custom','claude').steps[0].title,'공통 분석 변경');});
 check('node model exceptions and launch runtime survive freezing',()=>{const p=presets.freeze('custom','codex');assert.equal(p.profiles.analysis.model,'codex-test-model');assert.equal(p.launch_runtime,'codex');assert.equal(p.version,3);});
 check('cycles and missing dependencies are rejected before saving',()=>{for(const deps of [['review'],['missing']]){const p=presets.get('custom');p.steps[0].deps=deps;assert.throws(()=>presets.save(p,3),/CYCLE|DEPENDENCY/);}});
 check('multiple tasks expand to node dependencies inside each workflow stage',()=>{const p=presets.get('quick-fix');p.id='parallel';p.track='C';p.steps.push({id:'review',title:'리뷰',role:'review',skill:null,deps:['implement']});presets.save(p,0);const v=presets.expand({workflow:{preset_id:'parallel'},launch_runtime:'codex',tasks:[{step_id:'implement',files:['a.js']},{step_id:'implement',files:['b.js']},{step_id:'review',files:['r.md']}]});assert.deepEqual(v.nodes[2].deps,['implement-1','implement-2']);assert.equal(v.workflow.hash.length,64);});
 check('a frozen definition remains usable after the custom preset is deleted',()=>{const frozen=presets.freeze('custom','codex');presets.remove('custom',3);assert.equal(frozen.steps[0].title,'Codex 분석');assert.throws(()=>presets.get('custom'),/UNKNOWN/);});
 const content='---\nname: review\ndescription: 코드 리뷰 지침\n---\n# 리뷰\n오류와 유지보수성을 확인한다.';
 skills.save({content},0,{source:'user',runtime:'ui',reason:'skill fixture'});const frozen=skills.freeze('review');
 check('skill contents are versioned and a node snapshot does not drift after editing',()=>{skills.save({content:content+'\n추가 점검'},1);assert.equal(frozen.body,'# 리뷰\n오류와 유지보수성을 확인한다.');assert.notEqual(skills.freeze('review').hash,frozen.hash);assert.equal(skills.list()[0].version,2);});
 check('unknown and escaped skill paths are rejected',()=>{assert.throws(()=>skills.freeze('missing'),/UNKNOWN_SKILL/);for(const value of ['../private.md','C:/private/SKILL.md','.claude/skills/../../private/SKILL.md'])assert.throws(()=>skills.save({path:value},0),/PATH|RESOURCE/);});
 const local=path.join(dir,'.claude/skills/local');fs.mkdirSync(local,{recursive:true});fs.writeFileSync(path.join(local,'SKILL.md'),'---\nname: local\ndescription: |\n  여러 줄\n  설명\n---\n지침');
 check('existing project skills can be discovered, registered and checked for drift',()=>{assert.equal(skills.discover()[0].name,'local');skills.save({path:'.claude/skills/local/SKILL.md'},0);assert.equal(skills.list().find(s=>s.name==='local').drift,false);fs.appendFileSync(path.join(local,'SKILL.md'),' 변경');assert.equal(skills.list().find(s=>s.name==='local').drift,true);});
 check('canvas positions persist separately per runtime and freeze with the preset',()=>{const p=presets.get('standard');p.id='positioned';p.steps[0].position={x:128,y:64};p.variants.codex.inherit_common=false;p.variants.codex.steps=structuredClone(p.steps);p.variants.codex.steps[0].position={x:512,y:160};presets.save(p,0);assert.deepEqual(presets.freeze(p.id,'claude').steps[0].position,{x:128,y:64});assert.deepEqual(presets.freeze(p.id,'codex').steps[0].position,{x:512,y:160});const frozen=presets.freeze(p.id,'claude');p.steps[0].position.x=256;presets.save(p,1);assert.equal(frozen.steps[0].position.x,128);presets.restore(p.id,1,2);assert.equal(presets.get(p.id).steps[0].position.x,128);});
 check('invalid layout saves cannot corrupt the previous preset version',()=>{const p=presets.get('positioned');for(const position of [{x:-1,y:0},{x:0,y:Infinity},{x:'0',y:0}]){p.steps[0].position=position;assert.throws(()=>presets.save(p,3),/POSITION/);}assert.equal(presets.get(p.id).version,3);});
 console.log('결과: '+checks+' PASS / 0 FAIL');
}finally{repo.store.close();}
