'use strict';
const assert=require('assert/strict'),fs=require('fs'),path=require('path'),os=require('os');
const {repository,git}=require('../../.claude/hooks/_harness-store'),{Coordinator}=require('../../.claude/hooks/_coordinator'),managed=require('../../.claude/hooks/_managed-work'),{sessionView}=require('../../.claude/hooks/_session-view');
const root=fs.mkdtempSync(path.join(os.tmpdir(),'harness-multisession-unit-'));let repo,count=0;
async function check(name,fn){await fn();count++;console.log('PASS '+name);}
(async()=>{
 git(root,['init','-q']);for(const file of ['prd.md','plan.md'])fs.writeFileSync(path.join(root,file),'# fixture');git(root,['add','.']);git(root,['-c','user.name=Harness','-c','user.email=harness@test','commit','-qm','fixture']);repo=repository(root);
 const c=new Coordinator(repo.store,{repo_id:repo.repo_id}),a=c.join({runtime:'claude',worktree:root,name:'UI window'}),b=c.join({runtime:'codex',worktree:root,name:'API window'});
 const spec={track:'C',title:'shared work',max_parallel:1,nodes:[{id:'one',files:['one.txt']},{id:'two',files:['two.txt']}]};const work=c.createWork(spec);c.authorize(work.work_id,{source:'user',reference:'test'},work.graph_hash);
 await check('work concurrency cap applies across sessions',()=>{const first=c.claim(a,work.work_id,'one'),second=c.claim(b,work.work_id,'two');assert.equal(first.status,'claimed');assert.equal(second.status,'waiting_capacity');assert.equal(second.blockers[0].session_id,a.session_id);});
 await check('unchanged waiting observation does not flood event log',()=>{const cursor=repo.store.snapshot().cursor;c.claim(b,work.work_id,'two');assert.equal(repo.store.snapshot().cursor,cursor);});
 await check('public sessions never expose ownership credentials',()=>{assert.equal(c.publicSession(a).token,undefined);assert.equal(c.snapshot().sessions[0].token_hash,undefined);});
 await check('rename retains identity and rejects empty names',()=>{assert.equal(c.rename(a.session_id,'Frontend').session_id,a.session_id);assert.throws(()=>c.rename(a.session_id,''),/INVALID_SESSION_NAME/);});
 await check('cooperative stop prevents new claims and keeps in-flight ownership',()=>{c.requestStop(a.session_id);assert.throws(()=>c.claim(a,work.work_id,'two'),/SESSION_STOP_REQUESTED/);assert.equal(c.node(work.work_id,'one').session_id,a.session_id);const n=c.node(work.work_id,'one');c.failRun(a,work.work_id,'one',n.run_id,n.epoch,'cleanup');c.leave(a);c.leave(b);});
 await check('a waiting session gets its turn before a fast session reclaims free capacity',()=>{const s=c.join({runtime:'claude',worktree:root}),t=c.join({runtime:'codex',worktree:root}),w=c.createWork({track:'C',title:'fair allocation',max_parallel:1,nodes:[{id:'A',files:['a.txt']},{id:'B',files:['b.txt']},{id:'C',files:['c.txt']}]});c.authorize(w.work_id,{source:'user',reference:'test'},w.graph_hash);const n=c.claim(s,w.work_id,'A');assert.equal(c.claim(t,w.work_id,'B').status,'waiting_capacity');c.failRun(s,w.work_id,'A',n.run_id,n.epoch,'release');assert.equal(c.claim(s,w.work_id,'C').status,'waiting_capacity');const owned=c.claim(t,w.work_id,'B');assert.equal(owned.status,'claimed');c.failRun(t,w.work_id,'B',owned.run_id,owned.epoch,'cleanup');c.leave(s);c.leave(t);});
 await check('recovery review rejects a stale UI epoch',()=>{const dead=new Coordinator(repo.store,{repo_id:repo.repo_id,isAlive:()=>false}),s=dead.join({runtime:'claude',worktree:root}),n=dead.claim(s,work.work_id,'one');dead.recover(s.session_id);assert.throws(()=>dead.releaseQuarantine(work.work_id,'one','reviewed',n.epoch),/STALE_OWNER/);dead.releaseQuarantine(work.work_id,'one','reviewed',n.epoch+1);});
 await check('projection separates window runtime, worker runtime and prior attempts',()=>{
  const s={session_id:'session',name:'Window',runtime:'codex',status:'active',pid:123,worker_pids:[],work_id:'work',heartbeat_at:100,joined_at:100},node={work_id:'work',node_id:'node',session_id:'session',run_id:'new',epoch:2,status:'verifying',files:[]};
  const agents=[{agent_id:'old',session_id:'session',node_id:'node',work_id:'work',run_id:'old',status:'running',execution_runtime:'claude'},{agent_id:'new',session_id:'session',node_id:'node',work_id:'work',run_id:'new',epoch:2,status:'running',execution_runtime:'claude'}];const v=sessionView({sessions:[s],nodes:[node],agents,works:[{work_id:'work',title:'Example'}]},{now:150,alive:()=>true});assert.equal(v.totals.agents,1);assert.equal(v.sessions[0].agents.find(a=>a.agent_id==='old').status,'superseded');assert.equal(v.sessions[0].agents.find(a=>a.agent_id==='new').status,'verifying');assert.equal(v.sessions[0].runtime,'codex');assert.equal(v.sessions[0].agents[0].execution_runtime,'claude');
 });
 await check('dead controller is attention state and never shows historical agents as live',()=>{const v=sessionView({sessions:[{session_id:'s',pid:123,runtime:'claude',status:'active',heartbeat_at:0}],agents:[{agent_id:'a',session_id:'s',status:'running'}],nodes:[]},{alive:()=>false});assert.equal(v.totals.attention,1);assert.equal(v.totals.agents,0);assert.equal(v.sessions[0].recovery_needed,true);});
 const tests=[{mode:'automated',format:'json',command:[process.execPath,'-e',"console.log(JSON.stringify({status:'passed',checks:1}))"]}];
 await check('two managed sessions finish a shared graph without duplicate execution',async()=>{
  const w=managed.create(repo,{track:'C',title:'competing sessions',max_parallel:2,prd:'prd.md',plan:'plan.md',nodes:['A','B','C','D'].map(id=>({id,files:[id+'.txt'],tests}))},'test request');let calls=0,peak=0,active=0;
  const runner=async(profile,prompt)=>{calls++;active++;peak=Math.max(peak,active);const p=JSON.parse(prompt.split('Context:\n')[1]);await new Promise(r=>setTimeout(r,80));active--;return {text:JSON.stringify({summary:'done',files:[{path:p.node_id+'.txt',content:'done'}]})};};
  const results=await Promise.all(['claude','codex'].map(runtime=>managed.run(repo,w.work_id,{runtime,jobs:1,max_wait_ms:30000,onNotice:()=>{},modelRunner:runner})));assert.ok(results.every(x=>x.status==='verified'));assert.equal(calls,4);assert.equal(peak,2);const nodes=w.nodes.map(id=>c.node(w.work_id,id));assert.ok(nodes.every(n=>n.attempts===1));assert.equal(new Set(nodes.map(n=>n.session_id)).size,2);
 });
 await check('stopping a runner drains its current node and leaves pending work resumable',async()=>{
  const w=managed.create(repo,{track:'C',title:'drain',prd:'prd.md',plan:'plan.md',nodes:['E','F'].map(id=>({id,files:[id+'.txt'],tests}))},'test request');let credential;
  const result=await managed.run(repo,w.work_id,{runtime:'codex',jobs:1,onNotice:()=>{},onSession:s=>credential=s,modelRunner:async()=>{c.requestStop(credential.session_id);return {text:JSON.stringify({summary:'done',files:[]})};}});assert.equal(result.status,'stopped');assert.equal(c.node(w.work_id,'E').status,'verified');assert.equal(c.node(w.work_id,'F').status,'pending');assert.equal(repo.store.get('session/'+credential.session_id).value.status,'closed');
 });
 console.log('결과: '+count+' PASS / 0 FAIL');
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(()=>repo?.store.close());
